# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.checkout("JLD")'
  - julia -e 'Pkg.build("BlockRegistrationScheduler"); Pkg.test("BlockRegistrationScheduler")'
